/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9fc',
        'surface-dim': '#dadadc',
        'surface-bright': '#f9f9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f6',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#424843',
        'inverse-surface': '#2f3133',
        'inverse-on-surface': '#f0f0f3',
        outline: '#727973',
        'outline-variant': '#c2c8c1',
        'surface-tint': '#466552',
        primary: '#001308',
        'on-primary': '#ffffff',
        'primary-container': '#0a2a1a',
        'on-primary-container': '#72937d',
        'inverse-primary': '#accfb7',
        secondary: '#416900',
        'on-secondary': '#ffffff',
        'secondary-container': '#b7f569',
        'on-secondary-container': '#457000',
        tertiary: '#0d1011',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#222526',
        'on-tertiary-container': '#8a8c8d',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#c7ebd2',
        'primary-fixed-dim': '#accfb7',
        'on-primary-fixed': '#012112',
        'on-primary-fixed-variant': '#2e4d3b',
        'secondary-fixed': '#b7f569',
        'secondary-fixed-dim': '#9dd850',
        'on-secondary-fixed': '#102000',
        'on-secondary-fixed-variant': '#304f00',
        'tertiary-fixed': '#e1e3e4',
        'tertiary-fixed-dim': '#c5c7c8',
        'on-tertiary-fixed': '#191c1d',
        'on-tertiary-fixed-variant': '#454748',
        background: '#f9f9fc',
        'on-background': '#1a1c1e',
        'surface-variant': '#e2e2e5',
      },
      fontFamily: {
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '20px',
      },
      boxShadow: {
        'ultra-soft': '0px 12px 24px rgba(0, 0, 0, 0.05)',
        'glass': '0 8px 32px 0 rgba(0, 0, 0, 0.1)',
      }
    }
  },
  plugins: [],
}
